[build]
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://rqfstisofqubhlcjrjyr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZnN0aXNvZnF1YmhsY2pyanlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NjAyMzIsImV4cCI6MjA3NzEzNjIzMn0.LQHWQvOQqHeiG5bPKlKbh-US-jXLVW5QIUgm8zyoWHo"